name: Corey Megown

url: https://cmegown.com
permalink: /:title/

exclude:
  - assets/scss
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE.md
  - package-lock.json
  - package.json
